import type { AppSettings, HexBridgeApi, RuntimeState } from '../../shared/contracts'

const champion = (
  id: number,
  alias: string,
  name: string,
  tier: number,
  winRate: number,
  roles: string[],
  title = '',
) => ({
  id,
  alias,
  name,
  title,
  roles,
    tier,
    winRate,
    championPickRate: null,
  patch: '16.15',
  date: '2026-08-10',
  source: 'tencent',
  iconUrl: `https://ddragon.leagueoflegends.com/cdn/16.15.1/img/champion/${alias}.png`,
  splashUrl: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/${alias}_0.jpg`,
})

export function createDemoApi(): HexBridgeApi {
  const champions = [
    champion(103, 'Ahri', '阿狸', 2, 0.528, ['法师', '刺客'], '九尾妖狐'),
    champion(81, 'Ezreal', '伊泽瑞尔', 1, 0.552, ['射手', '法师'], '探险家'),
    champion(63, 'Brand', '布兰德', 1, 0.547, ['法师'], '复仇焰魂'),
    champion(89, 'Leona', '蕾欧娜', 3, 0.514, ['坦克', '辅助'], '曙光女神'),
    champion(51, 'Caitlyn', '凯特琳', 2, 0.535, ['射手'], '皮城女警'),
    champion(154, 'Zac', '扎克', 2, 0.531, ['坦克', '战士'], '生化魔人'),
  ]
  const current = {
    ...champions[0]!,
    sourceType: 'current' as const,
    isCurrent: true,
    isBest: false,
    winRateDelta: 0,
  }
  const bench = champions.slice(1, 5).map((item, index) => ({
    ...item,
    sourceType: 'bench' as const,
    isCurrent: false,
    isBest: index === 0,
    winRateDelta: item.winRate - current.winRate,
  }))
  const settings: AppSettings = {
    visualMode: 'auto',
    autoOcr: false,
    showChampionPanel: true,
    showInGameRecommendations: true,
    opponentScouting: true,
    lobbyBackground: false,
    wallpaperEngineEnabled: false,
    recommendationDataSource: 'dtodo',
    hotkey: 'F8',
    displayId: '',
    calibration: null,
    diagnosticsScreenshots: false,
  }
  const demoState: RuntimeState = {
    lcu: { connected: true, source: 'process', lastError: null, lastConnectedAt: Date.now() },
    snapshot: {
      phase: 'ChampSelect',
      locale: 'zh_CN',
      queueId: 2400,
      modeActive: true,
      matchStage: 'selecting',
      matchGeneration: 1,
      currentChampionId: current.id,
      benchChampionIds: bench.map((item) => item.id),
      benchEnabled: true,
      updatedAt: Date.now(),
    },
    api: {
      configured: true,
      status: 'ready',
      gamePatch: '16.15',
      dataVersion: '16.15.6',
      publishedAt: '2026-08-10',
      lastError: null,
    },
    recommendation: {
      source: 'dtodo',
      status: 'ready',
      snapshotId: '16.15.6',
      dataVersion: '16.15.6',
      statisticsDate: '2026-08-10',
      stale: false,
      lastError: null,
    },
    update: {
      status: 'up-to-date',
      currentVersion: '0.1.68',
      availableVersion: null,
      releaseName: null,
      releaseNotes: '',
      percent: null,
      transferred: null,
      total: 198_000_000,
      bytesPerSecond: null,
      downloadMode: null,
      downloadModeMessage: '',
      lastCheckedAt: Date.now(),
      errorCode: null,
      message: '当前已是最新版本',
    },
    releaseHighlights: null,
    champions,
    candidates: [current, ...bench],
    currentRecommendation: {
      source: 'dtodo',
      championId: current.id,
      snapshotId: '16.15.6',
      dataVersion: '16.15.6',
      statisticsDate: '2026-08-10',
      stale: false,
      message: '已读取 3 项英雄推荐',
      cards: [
        { augmentId: 1, name: '珠光护手', iconUrl: '', rarityName: '棱彩', description: '', recommendationRank: 1, reason: '该英雄适配度排名第 1', championPickRate: .24, globalPickRate: null, globalWinRate: null, globalPickRank: null, globalWinRank: null, globalPickRankChange: null, globalWinRankChange: null },
        { augmentId: 2, name: '法术苏醒', iconUrl: '', rarityName: '黄金', description: '', recommendationRank: 2, reason: '该英雄适配度排名第 2', championPickRate: .18, globalPickRate: null, globalWinRate: null, globalPickRank: null, globalWinRank: null, globalPickRankChange: null, globalWinRankChange: null },
        { augmentId: 3, name: '终极刷新', iconUrl: '', rarityName: '棱彩', description: '', recommendationRank: 3, reason: '该英雄适配度排名第 3', championPickRate: null, globalPickRate: null, globalWinRate: null, globalPickRank: null, globalWinRank: null, globalPickRankChange: null, globalWinRankChange: null },
      ],
    },
    currentChampionLevel: 8,
    currentBuild: {
      label: '爆发法师',
      patch: '16.15',
      source: 'iesdev',
      startingItems: [
        { id: 1056, name: '多兰之戒', iconUrl: 'https://cdn.dtodo.cn/hextech/item-icons/1056.png' },
        { id: 2003, name: '生命药水', iconUrl: 'https://cdn.dtodo.cn/hextech/item-icons/2003.png' },
      ],
      coreItems: [
        { id: 6655, name: '卢登的伙伴', iconUrl: 'https://cdn.dtodo.cn/hextech/item-icons/6655.png' },
        { id: 3020, name: '法师之靴', iconUrl: 'https://cdn.dtodo.cn/hextech/item-icons/3020.png' },
        { id: 4645, name: '影焰', iconUrl: 'https://cdn.dtodo.cn/hextech/item-icons/4645.png' },
      ],
      situationalItems: [
        { id: 3089, name: '灭世者的死亡之帽', iconUrl: 'https://cdn.dtodo.cn/hextech/item-icons/3089.png' },
        { id: 3135, name: '虚空之杖', iconUrl: 'https://cdn.dtodo.cn/hextech/item-icons/3135.png' },
      ],
    },
    opponentScout: {
      status: 'ready',
      reason: 'ready',
      matchGeneration: 1,
      sampledAt: Date.now(),
      source: 'local-lcu',
      message: '已本地汇总队友与对手最近 20 场',
      allySummary: { playerCount: 1, ratedCount: 1, sampleSize: 16, rating: 68, tier: '上等马', winRate: .625, kda: 3.4, confidence: 'supported' },
      opponentSummary: { playerCount: 3, ratedCount: 2, sampleSize: 47, rating: 65, tier: '上等马', winRate: 26 / 47, kda: 3.11, confidence: 'partial' },
      allies: [
        { opaqueKey: 'ally_demo_key_0000000001', relation: 'ally', slot: 1, championId: 103, status: 'ready', rating: 68, tier: '上等马', sampleSize: 16, wins: 10, losses: 6, winRate: .625, kda: 3.4, streak: 2 },
      ],
      opponents: [
        { opaqueKey: 'opponent_demo_key_000001', relation: 'opponent', slot: 1, championId: 63, status: 'ready', rating: 72, tier: '上等马', sampleSize: 20, wins: 14, losses: 6, winRate: .7, kda: 3.62, streak: 3 },
        { opaqueKey: 'opponent_demo_key_000002', relation: 'opponent', slot: 2, championId: 89, status: 'ready', rating: 54, tier: '中等马', sampleSize: 18, wins: 9, losses: 9, winRate: .5, kda: 2.91, streak: -1 },
        { opaqueKey: null, relation: 'opponent', slot: 3, championId: 51, status: 'ready', rating: null, tier: null, sampleSize: 9, wins: 3, losses: 6, winRate: 1 / 3, kda: 1.84, streak: -3 },
      ],
    },
    overlay: {
      visible: true,
      championId: current.id,
      detectedAt: Date.now(),
      message: '推荐已更新',
      slots: [
        { slot: 'left', rawText: '珠光护手', augmentId: 101, name: '珠光护手', confidence: .98, position: 2, tied: false, reason: '英雄专属排名 #8 / 167', iconUrl: '', rarityName: '棱彩', pickRate: .184, globalPickRate: null, globalWinRate: null, globalPickRank: null, globalWinRank: null, recommendationSource: 'dtodo', statisticsDate: '', metricScope: 'champion', statsSource: 'tencent', statsRegion: 'CN' },
        { slot: 'center', rawText: '万用瞄准镜', augmentId: 102, name: '万用瞄准镜', confidence: .97, position: 1, tied: false, reason: '英雄专属排名 #3 / 167', iconUrl: '', rarityName: '金色', pickRate: .267, globalPickRate: null, globalWinRate: null, globalPickRank: null, globalWinRank: null, recommendationSource: 'dtodo', statisticsDate: '', metricScope: 'champion', statsSource: 'tencent', statsRegion: 'CN' },
        { slot: 'right', rawText: '加速巫术', augmentId: 103, name: '加速巫术', confidence: .95, position: 3, tied: false, reason: '英雄专属 Tier 3', iconUrl: '', rarityName: '银色', pickRate: null, globalPickRate: null, globalWinRate: null, globalPickRank: null, globalWinRank: null, recommendationSource: 'dtodo', statisticsDate: '', metricScope: null, statsSource: null, statsRegion: null },
      ],
    },
    wallpaperEngine: {
      supported: true,
      configured: true,
      status: 'disabled',
      championId: null,
      errorCode: null,
      message: 'Wallpaper Engine 联动已关闭',
    },
    settings,
    displays: [{ id: '1', label: '显示器 1（主）', width: 2560, height: 1440, scaleFactor: 1, primary: true }],
    diagnostics: {
      ocrReady: true,
      ocrBusy: false,
      ocrLastDurationMs: 284,
      ocrLastError: null,
      ocrSchedule: {
        phase: 'latched',
        nextDelayMs: 700,
        cheapProbeCount: 18,
        cheapProbeLastDurationMs: 42,
        cheapProbeMaxDurationMs: 67,
        fullOcrCount: 2,
        fullOcrLastDurationMs: 284,
        fullOcrMaxDurationMs: 301,
        lastOutcome: 'matched',
      },
      manualOcrStatus: 'matched',
      manualOcrCode: 'MATCHED',
      manualOcrSource: 'hotkey',
      manualOcrTriggeredAt: Date.now(),
      manualOcrMessage: '已识别三张海克斯',
      polling: true,
      activeVisualMode: 'balanced',
      gpuAcceleration: true,
      presentation: {
        observer: 'observing',
        championCompanion: 'visible',
        augmentCompanion: 'visible',
      },
      logLines: ['2026-08-11T10:18:03 INFO LCU credentials discovered', '2026-08-11T10:18:04 INFO Data catalogs updated'],
    },
  }

  return {
    getState: async () => demoState,
    onStateChanged: () => () => undefined,
    updateSettings: async (patch: Partial<AppSettings>) => {
      demoState.settings = { ...demoState.settings, ...patch }
      return demoState.settings
    },
    setOcrHotkey: async (hotkey: string) => {
      demoState.settings.hotkey = hotkey
      return { ok: true, activeHotkey: hotkey, errorCode: null, message: `识别快捷键已设为 ${hotkey}` }
    },
    validateAndSaveApiKey: async () => ({ ok: true, message: '预览模式：验证成功' }),
    clearApiKey: async () => undefined,
    refreshData: async () => ({ ok: true, message: '预览模式：数据已刷新' }),
    getChampionRecommendation: async (championId) => ({
      ok: true,
      message: '预览模式：英雄推荐已读取',
      detail: {
        source: 'dtodo',
        championId,
        snapshotId: '16.15.6',
        dataVersion: '16.15.6',
        statisticsDate: '2026-08-10',
        stale: false,
        message: '英雄推荐已读取',
        cards: demoState.currentRecommendation?.cards ?? [],
      },
    }),
    getChampionBuild: async () => ({ ok: true, message: '预览模式：出装推荐已读取', build: demoState.currentBuild }),
    applyUpdate: async () => {
      demoState.update = { ...demoState.update, status: 'downloaded', percent: 100, message: '更新已下载' }
      return { ok: true, message: demoState.update.message }
    },
    openDeveloperPage: async () => ({ ok: true, message: '预览模式：打开 API Key 申请页' }),
    dismissReleaseHighlights: async () => { demoState.releaseHighlights = null },
    triggerOcr: async () => ({ ok: true, message: '预览模式：识别完成' }),
    retryOpponentScout: async () => ({ ok: true, message: '已本地汇总队友与对手最近 20 场' }),
    getScoutPlayerDetails: async (opaqueKey, matchGeneration) => ({
      ok: true,
      message: '已读取本机缓存明细',
      details: {
        opaqueKey,
        matchGeneration,
        relation: opaqueKey.startsWith('ally') ? 'ally' : 'opponent',
        slot: 1,
        championId: 63,
        matches: [{ championId: 63, win: true, kills: 8, deaths: 2, assists: 12, durationMinutes: 19 }],
      },
    }),
    getWallpaperEnginePreferences: async () => ({
      championTargetType: 'profile',
      championTargetTemplate: 'HexBridge-{id}',
      restoreTarget: { type: 'profile', name: 'HexBridge-Restore' },
    }),
    saveWallpaperEnginePreferences: async () => ({ ok: true, message: '预览模式：Wallpaper Engine 配置已保存' }),
    retryWallpaperEngine: async () => ({ ok: true, message: '预览模式：已重试 Wallpaper Engine' }),
    clearDiagnosticScreenshots: async () => ({ ok: true, message: '预览模式：没有诊断截图' }),
    retryLcuConnection: async () => ({ ok: false, message: '预览模式：未连接客户端' }),
    startCalibration: async () => undefined,
    getCalibrationContext: async () => null,
    previewCalibration: async () => ({ ok: true, names: ['由心及物', '冰寒', '虹吸'], message: '识别验证通过' }),
    completeCalibration: async (rects) => { demoState.settings.calibration = rects },
    cancelCalibration: async () => undefined,
    windowAction: async () => undefined,
  }
}
